### ISSUE TITLE
Demo for evolutility-ui-react (not an issue)

### ISSUE THREAD

**Issue by pymeup** [evoluteur/evolutility-ui-react#12]
Hello Oliver,

Really impressed by Evolutility so far, congrats!

I see that you have a Demo for the jquery version of the FrontEnd, do you plan to showcase one also for the React? 

Looking forward to see it!

Many thanks,
Costin V.

**Comment by evoluteur** [comment]
Yes, I'd like to have a live demo. 
Not sure if it will be w/ localStorage or a hosted Evolutility-Server-Node...
