### ISSUE TITLE
package-lock.json http: regressions

### ISSUE THREAD

**Issue by david-pfx** [evoluteur/evolutility-ui-react#14]
The new version 0.2.0 has a `package-lock.json`, for the first time AFAIK. It contains a mixture of http: and https:, which is undesirable in its own right, but also causes a heap of regressions when updating from an earlier version in which the file was locally generated.

My guess is that the simplest solution is not to include this file in the release.

**Comment by evoluteur** [comment]
It is recommended to check it in. I'll keep it for now.
