### ISSUE TITLE
Search function

### ISSUE THREAD

**Issue by pilgrim2go** [evoluteur/evolutility-ui-react#2]
Hi,

Thanks for your great app. I'm able to add new model with less effort.

I have some questions
+ Do you support `search` functionality?
I can't find any example using `search`. I also find that the search flag is commented.
+ Since I'm very new to `react`, can you give me a guidance to add `search` to a specific model?
I have one model only so we can accept `hard` approach.

Thanks,
Van

**Comment by evoluteur** [comment]
Hi Van,

The search is not implemented yet. I would like to upgrade to React 16.5.2 first and it is a big change...

**Comment by evoluteur** [comment]
Working on it...

**Comment by pymeup** [comment]
Hi Olivier,

Is it possible to have an estimate for when the Search functionality will be in place?

Thank you,
Costin V.

**Comment by pymeup** [comment]
Hi Olivier,

Kind reminder.

Thank you!
Costin V

**Comment by evoluteur** [comment]
Sorry, I thought I would find time to finish it. I'll checkin something within a week or 2 but I do not know when it will be really complete.

**Comment by pymeup** [comment]
ok , @evoluteur .

Looking forward to any upgrades as this implementation will be a great enhancement.

Thank you!

**Comment by evoluteur** [comment]
I checked-in the search feature. It doesn't include "lov" fields yet but gives you basic search for fields with string values.
Fields that are searched are specified in the models server-side.
Let me know how it's working for you.

**Comment by pymeup** [comment]
Hi Olivier,

Thank you for the update! Looking good!

Search is definitely helpful but Is filtering also a thing you are considering?

I think in the context of having to select from multiple columns the filtering would be a considerable advantage.

Nevertheless, really thanks for the implementation!

All the best,
Costin V.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by evoluteur** [comment]
I plan to have both search and filters.
Here is my prototype for filters: https://github.com/evoluteur/structured-filter-react

**Comment by david-pfx** [comment]
Which says: 

> React component for structured queries like "Contacts where Firstname starts with 'A' and Birthday before 1/1/2000 and State in (CA, NY, FL)"... 

That would not be my choice. I would much prefer (as in Excel and others) to set a condition and sort on each column.

**Comment by evoluteur** [comment]
Yes, a filter on each column is very convenient. I would still need the "query builder" style filter for cases where there is no table like in charts (which will use filters) or "saved queries". Ideally I should have both (in addition to search).
