### ISSUE TITLE
CORS issue (Response for preflight is invalid)

### ISSUE THREAD

**Issue by nick-tate** [evoluteur/evolutility-ui-react#5]
Running into an issue working with the React-UI and Node-Server backed on the same localhost for seemingly "non-simple" requests meaning all of the base GET API calls to the backend work fine, but trying to use the edit views for PUT API calls are getting interrupted. The React-UI will throw a Network Error - and digging into the developer console its looking like a CORS-related issue.

http://localhost:2000/api/V1/winecellar/5: Response for preflight is invalid (redirect)

I'm curious if anyone else has encountered this issue while trying to stand up the base apps.

**Comment by david-pfx** [comment]
Works fine for me. Windows 10.

**Comment by evoluteur** [comment]
It work fine for me on a Mac.
You may need to change the header options in app.js (lines 34 to 37) in Evolutility-Server-Node.

**Comment by evoluteur** [comment]
It should be filed in Evolutility-Server-Node rather than Evolutility-UI-React.
I'll close it here you can reopen it there.
Thanks.
