### ISSUE TITLE
LOV based on existing Entity returns no data

### ISSUE THREAD

**Issue by nick-tate** [evoluteur/evolutility-ui-react#6]
Trying to work backwards off of your template models to expand upon them. Looking at Winetasting.js and specifically the `wine_id` field:

` { 
            id: 'wine_id', entity: 'winecellar', column: 'wine_id', type: 'lov', 
            label: 'Wine', inMany: true,
            width: 62,
            required: true
        },`

When I attempt to add a new winetasting record or edit an existing, the LOV drop down list does not populate with available Wines. Is this field type intended to work as such? Attempting to rejoin the normalized structure that is created through the use of the LOV field type is tricky.

**Comment by evoluteur** [comment]
I had a regression in Evolutility-Server-Node. It is now fixed in version 0.5.2.
