### ISSUE TITLE
Date format is US only

### ISSUE THREAD

**Issue by david-pfx** [evoluteur/evolutility-ui-react#7]
All dates displayed by Evolutility seem to be in US format (mm/dd/yyyy). 
The culprit code appears to be this line in format.js:64.

`return dateParts[1]+'/'+dateParts[2]+'/'+dateParts[0];`

It really does need to format dates according to national preferences (mine are European dd/mm/yyyy).

**Comment by david-pfx** [comment]
This check-in on the naxl-ui fork uses `moment` to format dates and times:

https://github.com/david-pfx/naxl-ui/commit/f07151535f6399be1b376a41b3dfc4da1cfbd8bd

**Comment by evoluteur** [comment]
Excellent. Please submit a pull request for me to merge it.
Thanks.

**Comment by david-pfx** [comment]
Sure thing, but unfortunately your latest check-in introduces a merge conflict (on field type literals). I need to resolve that first.

**Comment by evoluteur** [comment]
I'd rather not introduce new dependencies.

**Comment by david-pfx** [comment]
I agree, but I don't think you can handle dates without a dependency on something. There is currently no dependency on moment, as all the mentions are commented out, so the field is open.

**Comment by david-pfx** [comment]
I'm on it.

**Comment by evoluteur** [comment]
Your pull request is in. Thanks again.
It is working. I can close this issue.

**Comment by david-pfx** [comment]
Please do. Happy to be able to help. 

I think it needs something in the readme, mentioning the issue of locales and browser settings and ensuring any needed locales have been included in the build. I'll leave that to you.
