### ISSUE TITLE
Browser history does not work with click sort

### ISSUE THREAD

**Issue by david-pfx** [evoluteur/evolutility-ui-react#8]
To reproduce, 
- click  on Todo. Displays the list.
- click on Title. Shows up arrow in the title bar.
- click on Title. Shows down arrow in the title bar and sorts list in descending order.
- click on back button. Display does not change (still descending). However, address bar now shows:
    `http://localhost:8080/todo/list?order=title.asc`
- click on Refresh. Display now shows ascending order.

As a side note, the title bar arrow does not always show correctly.

**Comment by evoluteur** [comment]
Fixed [96a4b80f5b42e39261617938c86d745de79dc00a](https://github.com/evoluteur/evolutility-ui-react/commit/96a4b80f5b42e39261617938c86d745de79dc00a).
I will check the title bar. Thanks.
