### ISSUE TITLE
Issues attempting to Dockerize

### ISSUE THREAD

**Issue by nick-tate** [evoluteur/evolutility-ui-react#9]
Has anyone attempted to Dockerize this code base? When I go to run the app via docker I get the following error and just trying to troubleshoot where I've gone wrong as I've mirrored the same steps with a normal "local" install without any issues.

> ERROR in ./src/components/views/many/Cards.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../One/Card in /evolutility-ui-react/src/components/views/many
resolve file
  /evolutility-ui-react/src/components/views/One/Card doesn't exist
  /evolutility-ui-react/src/components/views/One/Card.webpack.js doesn't exist
  /evolutility-ui-react/src/components/views/One/Card.web.js doesn't exist
  /evolutility-ui-react/src/components/views/One/Card.js doesn't exist
  /evolutility-ui-react/src/components/views/One/Card.json doesn't exist
resolve directory
  /evolutility-ui-react/src/components/views/One/Card doesn't exist (directory default file)
  /evolutility-ui-react/src/components/views/One/Card/package.json doesn't exist (directory description file)
[/evolutility-ui-react/src/components/views/One/Card]
[/evolutility-ui-react/src/components/views/One/Card.webpack.js]
[/evolutility-ui-react/src/components/views/One/Card.web.js]
[/evolutility-ui-react/src/components/views/One/Card.js]
[/evolutility-ui-react/src/components/views/One/Card.json]
 @ ./src/components/views/many/Cards.js 25:12-34

**Comment by evoluteur** [comment]
I made some changes since this issue was filed but now the path should use "/one/" not "/One/".
"/evolutility-ui-react/src/components/views/One/Card" should be "/evolutility-ui-react/src/components/views/one/Card".
